add ++macroinfo and macro aliases. Closes #5
the-programmers-hangout/Polly pull request #7
Opened 2020-11-22 05:22 UTC by hhhapz

2020-11-22 16:03 UTC, amhndu requested changes

2020-11-22 16:03 UTC, amhndu commented on src/main/kotlin/me/moeszyslak/polly/commands/MacroCommands.kt
> +            macroService.macroInfo(this, guild.id.longValue, args.first, args.second)
Is it not possible to do `respond(macroService.macroInfo(..))` like all the other commands? Better to keep the service as focused and as "pure" as possible.

2020-11-22 16:03 UTC, amhndu commented on src/main/kotlin/me/moeszyslak/polly/data/MacroStore.kt
> +            (channel == null || channel == "" || channel == textChannel.id.value).also { println("$name - $it") }
stray print?

2020-11-22 16:03 UTC, amhndu commented on src/main/kotlin/me/moeszyslak/polly/data/MacroStore.kt
> +    fun fullName() = "$name#${channel ?: ""}"
`"$name#${this.channel()}"`?

2020-11-22 16:03 UTC, amhndu commented on src/main/kotlin/me/moeszyslak/polly/services/MacroService.kt
> +        val (name, aliases) = nameRaw
Why is parsing done here? It should either be done using a DiscordKt `MultiArg` or done inside the command block and the list passed here

2020-11-22 16:03 UTC, amhndu commented on src/main/kotlin/me/moeszyslak/polly/services/MacroService.kt
> +                macros["$it#$channelId"] = parent.copy(name = it, parent = fullName, aliases = listOf())
The parent-child thing looks unnecessarily complicated and it's also duplicating aliases in the macro store and persisted data. Can we do something simpler? For example, we keep only "real" macros in the main macro store and then have a different non-persistent map of aliases (including the canonical name) to the canonical. This does the constant time lookup for an alias as well as avoid some bit of hassle managing the macro copies in the store. After any update to the map, you just regenerate this, thus you only need one small piece of code and everything else almost stays the same. This alias map can either go in the MacroStore (but marked Transient so it's not persistent) or in the MacroService.

2020-11-23 15:09 UTC, hhhapz commented on src/main/kotlin/me/moeszyslak/polly/commands/MacroCommands.kt
> +            macroService.macroInfo(this, guild.id.longValue, args.first, args.second)
The issue is that I want to be able to respond with either a string or an embed, and I access `guild` of the event within the Service, which is why I decided to go with this. It's done similarly for `List(All)Macros` and `MacroStats` too. Let me know if you think I should change it to only respond with an embed and make it pure.

2020-11-23 15:21 UTC, amhndu commented on src/main/kotlin/me/moeszyslak/polly/commands/MacroCommands.kt
> +            macroService.macroInfo(this, guild.id.longValue, args.first, args.second)
Okay it is fine as is then.

2020-11-27 17:10 UTC, amhndu approved these changes

2020-11-27 17:10 UTC, amhndu commented on src/main/kotlin/me/moeszyslak/polly/data/MacroStore.kt
> +    val aliases: MutableMap<GuildId, MutableMap<String, Macro>> = mutableMapOf()
I was thinking `MutableMap<String, String>` instead of `MutableMap<String, Macro>` but this is also fine.

2020-11-27 17:10 UTC, amhndu commented on src/main/kotlin/me/moeszyslak/polly/data/MacroStore.kt
> +            aliases[guildId]!!["${macro.name}#${macro.channel()}"] = macro.copy(parent = macro.name)
optional: does this need to be a copy? Can't it just share the ref?

2020-11-27 17:10 UTC, amhndu commented on src/main/kotlin/me/moeszyslak/polly/data/MacroStore.kt
> +        var parent: String = "",
optional: do we still need this parent?

2020-11-27 17:10 UTC, amhndu commented on src/main/kotlin/me/moeszyslak/polly/services/MacroService.kt
> +        }?.let {
optional: can't we just use an if-statement?
Simplicity trumps trying to use fancy features

2020-11-30 10:52 UTC, Moe-Szyslak commented
LGTM

2020-11-30 10:52 UTC, merged